### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#12]
When you launch a utility, I see the error:

```cmd
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/C:/workspace/git_clones/vortex-0.10.1/lib/guice-4.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

I am not sure what this means, but it suggests you might want to report this somewhere.

**Comment by tombrauer** [comment]
@danhamill are you launching from source? Let me know if you need any help setting up a dev environment.

I noticed this warning after the migration to Java 11. It has to do with java's new module system. Anyhow, I think the problem will be resolved when I upgrade to NetCDF's Java 11 compliant 5.* or 6.* series jars. I haven't made the change yet because it'll require some updates on my part for their API updates. There shouldn't be any loss in functionality in the current configuration, just some ugly warning messages.
