### ISSUE TITLE
cant find gdal_KEA.dll

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#50]
I am scripting against the vortex api and setting up my environment like:

```cmd
set "VORTEX_HOME=C:\Local_Software\vortex-0.10.24"
set "PATH=%VORTEX_HOME%\bin;%VORTEX_HOME%\bin\gdal;%PATH%"
set "GDAL_DRIVER_PATH=%VORTEX_HOME%\bin\gdal\gdalplugins"
set "GDAL_DATA=%VORTEX_HOME%\bin\gdal\gdal-data"
set "PROJ_LIB=%VORTEX_HOME%\bin\gdal\projlib"
set "CLASSPATH=%VORTEX_HOME%\lib\*"


C:\jython2.7.2\bin\jython.exe -Djava.library.path=%VORTEX_HOME%\bin;%VORTEX_HOME%\bin\gdal C:\workspace\RTI\scripts\vortex\import_HMET.py
cmd /k
```

and I am getting errors during the imports at the top of the jython script.

```cmd
ERROR 1: Can't load requested DLL: C:\Local_Software\vortex-0.10.24\bin\gdal\gdalplugins\gdal_KEA.dll
127: The specified procedure could not be found.
```

**Comment by tombrauer** [comment]
This error is non-consequential for Vortex because we are not typically dealing with KEA files. You can delete the line that sets the GDAL_DRIVER_PATH variable from your batch script, and the error should go away. Vortex doesn't use the KEA plugin, or any other GDAL plugins, so setting the GDAL_DRIVER_PATH isn't neccesary.

**Comment by danhamill** [comment]
Ok, thanks.  I was also questioning why we needed `GDAL_DRIVER_PATH`.  

Everything from the import process appears to be correct.
