### ISSUE TITLE
Replace DSS files?

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#72]
using release v0.10.28-rc.6 I am getting prompted by windows that an existing dss file will be replaced.

![image](https://user-images.githubusercontent.com/11522898/172715382-f0e8f0fb-45b4-4f95-8b06-af637cec01c7.png)

Does that mean vortex is now overwriting a pre-existing dss file?

**Comment by tombrauer** [comment]
I changed from an Open file dialog to a Save file dialog. With a Save file dialog you can specify a file that does not exist. With an Open file dialog, the file must exist to be selected. With the Save file dialog, there is an overwrite warning prompt if the file already exists. In this case only records that previously exist in the DSS file will be overwritten, otherwise the existing DSS file will be appended. Do you think I should change back to and Open dialog? I thought a Save dialog might be easier for people who want to create a new DSS file that doesn't already exist, i.e. they don't have to use DSSVue to create the file beforehand. Acknowledged, you can avoid the file browser entirely and designate a path to a non-existent DSS file, and it will be created when vortex goes to write. I think alot of people use the file browser dialog to help create the path, rather than typing it out manually from start to finish.

**Comment by danhamill** [comment]
I think a save dialog is best.  I always got frustrated with open dialog.  I would use the open dialog navigate to the root I wanted to save the file in, copy the path, close the open dialog, then paste and complete the filename in the vortex UI.

For a long time, I did not think vortex could create new dss files.  A save dialog makes that option easier to understand.
