### ISSUE TITLE
Question:  Convert deg C to deg F

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/Vortex#8]
Can Vortex be used to convert grid units degC to degF?

**Comment by tombrauer** [comment]
You can change the units string but there is not currently any capability to do a raster calculator type operation on the grid values. For HMS, we usually leave the temperature data as degrees C because HMS will do data conversions on the fly. The internal engine calculations are actually all done in metric, with a few exceptions.
