### ISSUE TITLE
Northwest RFC AORC 1KM Data

### ISSUE THREAD

**Issue by coag2005** [HydrologicEngineeringCenter/Vortex#82]
The 1KM AORC precipitation dataset produced by the Northwest River Forecast Center doesn't properly display the date range (part D and Part E) when using "Importer" to convert NetCDF to DSS. I have not tried the temperature or other parameters yet. The 4KM AORC data from all the RFCs work as expected but this is my first time working with 1KM data and I ran into this date/time issue. For reference, the date range expected (and working on the 4KM dataset) is early December 2007.

1KM Dataset Link:
https://hydrology.nws.noaa.gov/aorc-historic/AORC_NWRFC/

![image](https://github.com/HydrologicEngineeringCenter/Vortex/assets/81264993/5984b752-8853-4f16-8928-8820d6d8898e)

**Comment by tombrauer** [comment]
The 1 KM AORC NetCDF files are missing a few things that make it really difficult to extract the correct times. First, a [Cell method](aorc-nwrfc_2023040100z.nc4) attribute can be used to indicate whether a gridded record can be attributed to an instant in time, or a measurement over a period. This dataset does not include a cell methods attribute. Second, a time bounds variable can be used to define the bounds for each time coordinate. This is another way to indicate period or instantaneous data. This dataset does not include a time bounds variable. 

The bogus dates happen because no time bounds are specified and there is only one coordinate on the time axis so time bounds can't be inferred from the sequence of dates on the time axis.

Can you ask the creators of this dataset to add a time bounds variable to the dataset?

**Comment by coag2005** [comment]
Tom, thanks for the response. I'll reach out to NWS OWP. Thanks!

**Comment by tombrauer** [comment]
I'm having trouble accessing the data for testing, but this should be better handled by the latest vortex release, v0.11.0.

First, [this fix](https://github.com/Unidata/netcdf-java/issues/1023) in the netcdf-java repo will better handle the dates for this case. I am guessing the start time and end time will be the same and correspond to the time axis value.

Second, I added the ability to time-shifter utility to shift _just_ the start time, or _just_ the end time.

So, if everything goes as I imagine it will, you would run the dataset through the importer. The imported grids will have the same start time and end time. Then you would run the grids through the time-shifter shifting the start time by -1 hours. 

If you have a few of the original netcdf files and are able to test let me know how it goes. Once again, you'll need to make sure you're using v0.11.0 or greater.

**Comment by coag2005** [comment]
Thanks for this. I will test it on Friday. Also, it looks like the data link may have changed. Here it is: https://hydrology.nws.noaa.gov/pub/aorc-historic/AORC_NWRFC/

**Comment by tombrauer** [comment]
Thanks, I tested an import with the files from the new location. The files use a more verbose naming convention similar to the 4 km files. Vortex recognizes these files as AORC and adjusts the start time accordingly. The generated HEC-DSS file needs no further modification. You should be able to import and then run in HEC-HMS.

**Comment by coag2005** [comment]
Very interesting. No worries, the time shift feature will work just fine. Again, thanks for all the help here!
